/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb --transform
Files: laptop.glb [1.31MB] > /Users/camerongaut/Projects/3dtest/public/models/laptop-transformed.glb [129.88KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.762, 0, -0.435]} rotation={[1.657, 0, 0]} scale={[1.572, 0.03, 1.433]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.macBook_BottomPart.geometry} material={materials.TopLine} position={[-1.071, 0.702, -1.863]} scale={[1.57, 0.032, 1.429]} />
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')
